### PR TITLE
[Task #79934] Design main page structure and navigation

### PR DESCRIPTION
**Pull request by minhsieu9102003**
ready

### CODE REVIEW

**Comment by minhsieu9102003** [comment]
ready

**Review by tuan-bach123 — APPROVED** [review]
maybe need to hide env file

**Review by mvansan — APPROVED** [review]

**Review by notverygood135 — APPROVED** [review]

**Review by sonnguyendev157 — APPROVED** [review]

**Comment by ghost** [comment]
đặt lại title pull request

**Comment by ghost** [comment]
conflic

**Pull request merged**
